ktor:
  application:
    modules:
      - dev.ansgrb.ApplicationKt.module
  deployment:
    port: 8080
    host: 0.0.0.0

#jwt:
#  secret = "russia"
#  issuer = "https://0.0.0.0:8080"
#  audience "https://0.0.0.0:8080"